package Form;

import Components.TableActionCellEditor;
import Components.TableActionCellRender;
import Components.TableActionEvent;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import helper.DistributorQueries;
import controller.DistributorController;

/**
 *
 * @author rafli
 */
public class Distributor extends javax.swing.JPanel {

    /**
     * Creates new form Distributor
     */
    public Distributor() {
        initComponents();
        DistributorController controller = new DistributorController(table1);
        controller.getData((DefaultTableModel) table1.getModel());
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                System.out.println("Edit row : " + row);
            }

            @Override
            public void onDelete(int row) {
                if (table1.isEditing()) {
                    table1.getCellEditor().stopCellEditing();
                }
                DefaultTableModel model = (DefaultTableModel) table1.getModel();
                model.removeRow(row);
            }

            @Override
            public void onView(int row) {
                System.out.println("View row : " + row);
            }
        };
        table1.getColumnModel().getColumn(5).setCellRenderer(new TableActionCellRender());
        table1.getColumnModel().getColumn(5).setCellEditor(new TableActionCellEditor(event));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new Components.Table();
        btnAdddistrib = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Master / Distributor");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Distributor", "Nama Distributor", "No Telepon", "Alamat Distributor", "Tanggal Daftar", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                table1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(table1);

        btnAdddistrib.setText("ADD DISTRIBUTOR");
        btnAdddistrib.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdddistrib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdddistribMouseClicked(evt);
            }
        });
        btnAdddistrib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdddistribActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdddistrib)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnAdddistrib)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void table1AncestorAdded(javax.swing.event.AncestorEvent evt) {// GEN-FIRST:event_table1AncestorAdded
        // TODO add your handling code here:

    }// GEN-LAST:event_table1AncestorAdded

    private void btnAdddistribActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAdddistribActionPerformed
        // TODO add your handling code here:
        try {
            // Create a JDialog as the parent for the AddDistributor panel
            JDialog dialog = new JDialog();

            // Create an instance of AddDistributor
            AddDistributor addDistributorPanel = new AddDistributor(table1);

            // Add the AddDistributor panel to the dialog
            dialog.getContentPane().add(addDistributorPanel);

            // Set properties for the dialog (adjust as needed)
            dialog.setSize(465, 450);
            dialog.setLocationRelativeTo(this); // Center the dialog relative to the Distributor panel

            // Make the dialog modal, blocking input to other windows
            dialog.setModal(true);

            // Set the default close operation to dispose the dialog
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

            // Set the dialog visible
            dialog.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace(); // Log the exception for debugging
        }
    }// GEN-LAST:event_btnAdddistribActionPerformed

    private void btnAdddistribMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnAdddistribMouseClicked
        // TODO add your handling code here:

    }// GEN-LAST:event_btnAdddistribMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdddistrib;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private Components.Table table1;
    // End of variables declaration//GEN-END:variables

}