package Form;

import Components.TableActionCellEditor;
import Components.TableActionCellRender;
import Components.TableActionEvent;
import controller.UserController;
import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafli
 */
public class UserForm extends javax.swing.JPanel {

    /**
     * Creates new form User
     */
    public UserForm() {
        initComponents();
        model.User user = new model.User();
        UserController controller = new UserController(tblUser);
        controller.showAllData((DefaultTableModel) tblUser.getModel());
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                PopUpUser dialog = new PopUpUser(tblUser, row);
                controller.getSingleData(row, tblUser, dialog);
//                dialog.setSize(934, 573);
                dialog.setLocationRelativeTo(UserForm.this); // Center the dialog relative to the Distributor panel
                // Make the dialog modal, blocking input to other windows
                dialog.setModal(true);
                //Set background color dialog
                dialog.getContentPane().setBackground(Color.WHITE);
                // Set the default close operation to dispose the dialog
                dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                // Set the dialog visible
                dialog.setVisible(true);
            }

            @Override
            public void onDelete(int row) {
                try{
                    controller.deleteDataUser();
                }catch(Exception e){
                    System.out.println("Error : " + e.getMessage());
                }
            }

            @Override
            public void onView(int row) {
                    System.out.println("View row : " + row);
            }
        };
        
        tblUser.getColumnModel().getColumn(3).setCellRenderer(new TableActionCellRender());
        tblUser.getColumnModel().getColumn(3).setCellEditor(new TableActionCellEditor(event));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUser = new Components.Table();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new Components.Table();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Settings / Manage User");

        jPanel1.setLayout(new java.awt.CardLayout());

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Jabatan", "Status", "Active"
            }
        ));
        jScrollPane2.setViewportView(tblUser);

        jPanel1.add(jScrollPane2, "card2");

        jPanel2.setLayout(new java.awt.CardLayout());

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aktifitas Pengguna"
            }
        ));
        jScrollPane3.setViewportView(table3);

        jPanel2.add(jScrollPane3, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private Components.Table table3;
    private Components.Table tblUser;
    // End of variables declaration//GEN-END:variables
}
