package Page;

import Components.MyIcon;
import controller.BarangController;
import controller.BarangKeluarController;
import controller.BarangMasukController;
import controller.DistributorController;
import controller.KlasifikasiController;
import helper.KategoriQueries;
import helper.SatuanQueries;
import java.awt.Font;
import javax.swing.ImageIcon;
import model.Card;

public class Dashboard extends javax.swing.JPanel {

    ImageIcon iconStaff = MyIcon.getIcon("staff");
    ImageIcon iconBarang = MyIcon.getIcon("item");
    ImageIcon iconCategory = MyIcon.getIcon("category");
    ImageIcon iconSatuan = MyIcon.getIcon("satuan");
    ImageIcon iconIncome = MyIcon.getIcon("income");
    ImageIcon iconOutbound = MyIcon.getIcon("outbound");
    ImageIcon iconDistributor = MyIcon.getIcon("distributor-2");
    Font font = new Font("Poppins", Font.BOLD, 18);

    public Dashboard() {
        initComponents();

        BarangController barangController = new BarangController();
        BarangKeluarController bkController = new BarangKeluarController();
        BarangMasukController bmController = new BarangMasukController();
        KlasifikasiController satuanController = new KlasifikasiController();
        KlasifikasiController kategoriController = new KlasifikasiController();
        DistributorController distributorController = new DistributorController();

        card1.setData(new Card(iconBarang, "Barang", barangController.getTotalBarang()));
        card2.setData(new Card(iconCategory, "Kategori Barang", kategoriController.getTotalData(KategoriQueries.SELECT_ALL_KATEGORI)));
        card3.setData(new Card(iconSatuan, "Satuan Barang", satuanController.getTotalData(SatuanQueries.GET_TOTAL_SATUAN)));
        card4.setData(new Card(iconOutbound, "Barang Keluar", bkController.getTotalData()));
        card5.setData(new Card(iconIncome, "Barang Masuk", bmController.getTotalData()));
        card6.setData(new Card(iconStaff, "Staff", "20"));
        card7.setData(new Card(iconDistributor, "Distributor", distributorController.getTotalDistributor()));
        card8.setData(new Card(iconDistributor, "Tanggal", "20"));
        title.setFont(font);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        cardContainer = new javax.swing.JLayeredPane();
        card1 = new Components.Card();
        card2 = new Components.Card();
        card3 = new Components.Card();
        card5 = new Components.Card();
        card4 = new Components.Card();
        card7 = new Components.Card();
        card6 = new Components.Card();
        card8 = new Components.Card();

        setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Dashboard");

        cardContainer.setLayout(new java.awt.GridLayout(2, 4, 15, 20));

        card1.setColor1(new java.awt.Color(0, 204, 204));
        card1.setColor2(new java.awt.Color(51, 255, 204));
        cardContainer.add(card1);

        card2.setColor1(new java.awt.Color(255, 204, 102));
        card2.setColor2(new java.awt.Color(255, 204, 0));
        cardContainer.add(card2);

        card3.setColor1(new java.awt.Color(51, 204, 0));
        card3.setColor2(new java.awt.Color(51, 255, 0));
        cardContainer.add(card3);

        card5.setColor1(new java.awt.Color(153, 0, 153));
        card5.setColor2(new java.awt.Color(102, 0, 102));
        cardContainer.add(card5);

        card4.setColor1(new java.awt.Color(255, 153, 51));
        card4.setColor2(new java.awt.Color(255, 153, 51));
        cardContainer.add(card4);

        card7.setColor1(new java.awt.Color(204, 204, 0));
        card7.setColor2(new java.awt.Color(204, 204, 0));
        cardContainer.add(card7);

        card6.setColor1(new java.awt.Color(255, 0, 0));
        card6.setColor2(new java.awt.Color(204, 0, 51));
        cardContainer.add(card6);

        card8.setColor2(new java.awt.Color(0, 0, 0));
        cardContainer.add(card8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(cardContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void table2KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_table2KeyReleased
        // TODO add your handling code here:
    }// GEN-LAST:event_table2KeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.Card card1;
    private Components.Card card2;
    private Components.Card card3;
    private Components.Card card4;
    private Components.Card card5;
    private Components.Card card6;
    private Components.Card card7;
    private Components.Card card8;
    private javax.swing.JLayeredPane cardContainer;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
