package Page;

import Form.Dashboard;
import Components.MenuItem;
import Form.Barang;
import Form.Distributor;
import Form.Staff;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JRootPane;

public class MainMenus extends javax.swing.JFrame {

    /**
     * Creates new form MainMenus
     */

    public MainMenus() {
        initComponents();
        execute();
        listMenu.setPreferredSize(new Dimension(350, 0));
        this.setUndecorated(true);
        // this.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        txtUsernameMain = new javax.swing.JLabel();
        humbMenu = new javax.swing.JLabel();
        profileImage = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMenu = new javax.swing.JPanel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMAG");
        setBackground(new java.awt.Color(204, 204, 204));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        navbar.setBackground(new java.awt.Color(255, 255, 255));
        navbar.setPreferredSize(new java.awt.Dimension(669, 70));

        title.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("SIMAG");

        txtUsernameMain.setBackground(new java.awt.Color(204, 204, 204));
        txtUsernameMain.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtUsernameMain.setForeground(new java.awt.Color(0, 0, 0));
        txtUsernameMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUsernameMain.setText("Admin");
        txtUsernameMain.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtUsernameMainAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        humbMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        humbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        humbMenu.setText("jLabel2");
        humbMenu.setMaximumSize(new java.awt.Dimension(26, 26));
        humbMenu.setMinimumSize(new java.awt.Dimension(26, 26));
        humbMenu.setPreferredSize(new java.awt.Dimension(26, 26));
        humbMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                humbMenuMouseClicked(evt);
            }
        });

        profileImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.png"))); // NOI18N
        profileImage.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(humbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 909, Short.MAX_VALUE)
                .addComponent(txtUsernameMain, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(humbMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUsernameMain)
                        .addComponent(title)
                        .addComponent(profileImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(navbar, java.awt.BorderLayout.PAGE_START);

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setPreferredSize(new java.awt.Dimension(160, 369));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        listMenu.setBackground(new java.awt.Color(255, 255, 255));
        listMenu.setPreferredSize(new java.awt.Dimension(0, 200));
        listMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listMenuMouseExited(evt);
            }
        });
        listMenu.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                listMenuComponentShown(evt);
            }
        });
        listMenu.setLayout(new javax.swing.BoxLayout(listMenu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(listMenu);

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        getContentPane().add(sidebar, java.awt.BorderLayout.LINE_START);

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new java.awt.BorderLayout());
        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1210, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        content.add(new Dashboard());
        content.repaint();
        content.revalidate();
    }// GEN-LAST:event_formWindowOpened

    private void listMenuMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_listMenuMouseExited
        // TODO add your handling code here:
    }// GEN-LAST:event_listMenuMouseExited

    private void listMenuMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_listMenuMouseEntered
        // TODO add your handling code here:
    }// GEN-LAST:event_listMenuMouseEntered

    private void listMenuComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_listMenuComponentShown
        // TODO add your handling code here:
    }// GEN-LAST:event_listMenuComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }// GEN-LAST:event_formComponentShown

    private void txtUsernameMainAncestorAdded(javax.swing.event.AncestorEvent evt) {// GEN-FIRST:event_txtUsernameMainAncestorAdded
        // TODO add your handling code here:
        txtUsernameMain.setText(Register.username + "");
    }// GEN-LAST:event_txtUsernameMainAncestorAdded

    private void humbMenuMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_humbMenuMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_humbMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel humbMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listMenu;
    private javax.swing.JPanel navbar;
    private javax.swing.JLabel profileImage;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel title;
    private javax.swing.JLabel txtUsernameMain;
    // End of variables declaration//GEN-END:variables

    private void execute() {

        ImageIcon iconMaster = new ImageIcon(getClass().getResource("/image/master.png"));
        ImageIcon iconBarang = new ImageIcon(getClass().getResource("/image/barang.png"));

        MenuItem menuBarang = new MenuItem(iconBarang, true, "Barang", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                content.removeAll();
                content.add(new Barang());
                content.repaint();
                content.revalidate();
            }
        });
        MenuItem menuBarang2 = new MenuItem(iconBarang, true, "Distributor", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                content.removeAll();
                content.add(new Distributor());
                content.repaint();
                content.revalidate();
            }
        });
        MenuItem menuBarang3 = new MenuItem(iconBarang, true, "Staff", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                content.removeAll();
                content.add(new Staff());
                content.repaint();
                content.revalidate();
            }
        });
        MenuItem menuMaster = new MenuItem(iconMaster, false, "Master", null, menuBarang, menuBarang2,
                menuBarang3);
        MenuItem menuDashboard = new MenuItem(null, false, "Dashboard", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                content.removeAll();
                content.add(new Dashboard());
                content.repaint();
                content.revalidate();
            }
        });

        MenuItem menuTransaction1 = new MenuItem(iconBarang, true, "Barang Masuk", null);
        MenuItem menuTransaction2 = new MenuItem(iconBarang, true, "Barang Keluar", null);
        MenuItem menuTransaction3 = new MenuItem(iconBarang, true, "Pemesanan", null);
        MenuItem menuTransaction = new MenuItem(null, false, "Transaksi", null, menuTransaction1, menuTransaction2,
                menuTransaction3);

        MenuItem menuReport1 = new MenuItem(iconBarang, true, "Transaksi", null);
        MenuItem menuReport2 = new MenuItem(iconBarang, true, "Kinerja Staff", null);
        MenuItem menuReport = new MenuItem(null, false, "Laporan", null, menuReport1, menuReport2);

        MenuItem menuSettings = new MenuItem(null, false, "Pengaturan", null);

        addMenu(menuDashboard, menuMaster, menuTransaction, menuReport, menuSettings);
    }

    private void addMenu(MenuItem... menu) {
        for (int i = 0; i < menu.length; i++) {
            listMenu.add(menu[i]);
            ArrayList<MenuItem> subMenu = menu[i].getSubMenu();
            for (MenuItem item : subMenu) {
                addMenu(item);
            }
        }
        listMenu.revalidate();
    }
}
